declare module '@editorjs/header';
declare module '@editorjs/list';
declare module '@editorjs/quote';
declare module '@editorjs/code';
declare module '@editorjs/image';
declare module '@editorjs/embed';
declare module '@editorjs/marker';
declare module '@editorjs/table';
declare module '@editorjs/checklist';
declare module '@editorjs/warning';
declare module '@editorjs/delimiter';
declare module '@editorjs/inline-code';
declare module '@editorjs/underline';
declare module '@editorjs/link';
declare module '@editorjs/raw';
declare module '@editorjs/paragraph';
declare module 'editorjs-text-color-plugin';
declare module 'editorjs-text-alignment-blocktune';
declare module 'editorjs-undo';
declare module 'editorjs-drag-drop';
declare module 'editorjs-style';

declare const DOMPurify: any;
